### ISSUE TITLE
使用cocoapods有问题

### ISSUE THREAD

**Issue by Young1006** [QuintGao/GKNavigationController#1]
使用 cocoapods 导入框架，找到GKNavigationBarConfigure这个类，设置相关属性时会报错

**Comment by QuintGao** [comment]
这个框架里面没有GKNavigationBarConfigure，你说的应该是另一个框架GKNavigationBarViewController

**Comment by QuintGao** [comment]
具体报什么错，能不能贴下代码

**Comment by YogaChen** [comment]
使用 cocoapods 安装, 编译时出现Code Sign Error

**Comment by QuintGao** [comment]
pod已更新至1.0.3
